<?php

namespace Abit\Blog\Block\Post;

use Exception;
use Magento\Cms\Model\Template\FilterProvider;
use Magento\Framework\Registry;
use Magento\Framework\View\Element\Template;

/**
 * @SuppressWarnings(PHPMD.CyclomaticComplexity)
 * @SuppressWarnings(PHPMD.NPathComplexity)
 */
class View extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Registry
     */
    private $_coreRegistry;
    /**
     * @var FilterProvider
     */
    private $filterProvider;

    public function __construct(
        Template\Context $context,
        Registry $registry,
        FilterProvider $filterProvider,
        array $data = []
    ) {
        $this->_coreRegistry = $registry;
        $this->filterProvider = $filterProvider;

        parent::__construct($context, $data);
    }

    public function _prepareLayout()
    {
        $post = $this->getPost();
        $this->pageConfig->getTitle()->set($post->getTitle());
        $this->pageConfig->setKeywords($post->getMetaKeywords());
        $this->pageConfig->setDescription($post->getMetaDescription());

        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    public function getPost()
    {
        $post = $this->_coreRegistry->registry('current_post');
        if ($post) {
            $this->setData('current_post', $post);
        }
        return $post;
    }

    /**
     * @return string
     * @throws Exception
     */
    public function getPostContent()
    {
        return $this->filterProvider->getPageFilter()->filter($this->getPost()->getPostContent());
    }
}
