<?php


namespace Abit\Blog\Model\ResourceModel;


use Magento\Framework\Model\AbstractModel;
use Magento\Framework\Model\ResourceModel\Db\AbstractDb;
use Magento\Framework\Model\ResourceModel\Db\Context;

class Cat extends AbstractDb
{

    public function __construct(Context $context)
    {
        parent::__construct($context);
    }

    /**
     * @inheritDoc
     */
    protected function _construct()
    {
        $this->_init('aw_blog_cat', 'cat_id');
    }

    protected function _afterLoad(AbstractModel $object)
    {
        if ($object->getId()) {
            $store_id = $this->lookupStoreIds($object->getId());
            $object->setData('store_id', $store_id);
        }
        return parent::_afterLoad($object); // TODO: Change the autogenerated stub
    }

    public function getCountPost($catId)
    {
        $connection = $this->getConnection();
        $select = $connection->select()->from(
            $this->getTable('aw_blog_post_cat'),
            'post_id'
        )->where(
            'cat_id = ?',
            (int)$catId
        );
        return $connection->fetchCol($select);
    }

    public function lookupStoreIds($postId)
    {
        $connection = $this->getConnection();
        $select = $connection->select()->from(
            $this->getTable('aw_blog_cat_store'),
            'store_id'
        )->where(
            'cat_id = ?',
            (int)$postId
        );
        return $connection->fetchCol($select);
    }
}
