<?php

use Abit\Blog\Block\Post\Recent;

/** @var Recent $block */
$postCollection = $block->getCollection()
    ->setPageSize($this->getPageSize());
?>

<div class="box-full">
	<h2 class="title-black title-mg0">Bài viết khác</h2>
	<div class="box-news slide-4-news">
		<ul class="ul-list-news slide4item">
		<?php if ($postCollection->count()): ?>
		<?php foreach ($postCollection as $post): ?>
			<li>
				<div class="item-news">
					<div class="img-news">
					<?php if ($post->getFeaturedImageUrl() && $post->getFeaturedShowOnHome()): ?>
						<a href="<?= $post->getUrl() ?>">
							<img
									src="<?= $post->getFeaturedImageUrl() ?>"
									alt="<?= $block->getFeaturedAlt($post) ?>"
								<?= $block->getImageWidth() ? "width=\"" . $block->getImageWidth() . "px\"" : '' ?>
								<?= $block->getImageHeight() ? "height=\"" . $block->getImageHeight() . "px\"" : '' ?>
							/>
						</a>
					<?php endif ?>
					</div>
					<a href="<?= $post->getUrl() ?>" class="link-news"><?= $post->getName() ?></a>
					<div class="desc-news">
						 <?= $post->getShortContent() ?>
					</div>
				</div>
			</li>
		<?php endforeach ?>
		<?php endif ?>
		</ul>
	</div>
</div>


