<?php

namespace Abit\Blog\Block\Cat;

use Exception;
use Magento\Cms\Model\Template\FilterProvider;
use Magento\Framework\Registry;
use Magento\Framework\View\Element\Template;

/**
 * @SuppressWarnings(PHPMD.CyclomaticComplexity)
 * @SuppressWarnings(PHPMD.NPathComplexity)
 */
class View extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Registry
     */
    private $_coreRegistry;
    /**
     * @var FilterProvider
     */
    private $filterProvider;

    public function __construct(
        Template\Context $context,
        Registry $registry,
        FilterProvider $filterProvider,
        array $data = []
    ) {
        $this->_coreRegistry = $registry;
        $this->filterProvider = $filterProvider;
        parent::__construct($context, $data);
    }

    public function _prepareLayout()
    {
        $category = $this->getCategory();
        $this->pageConfig->getTitle()->set($category->getTitle());
        $this->pageConfig->setKeywords($category->getMetaKeywords());
        $this->pageConfig->setDescription($category->getMetaDescription());

        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    public function getCategory()
    {
        $category = $this->_coreRegistry->registry('current_blog_cat');

        if ($category) {
            $this->setData('current_blog_cat', $category);
        }
        return $category;
    }
}
